import type { Form33AManagementRule } from "./form33a-rules";

export const form32BFeeRules = {
  gstRate: 0.15,
  mileageRatePerKm: 1.20,
  fixedFees: {
    preHearingMatters: 620,
    complyingJudgesDirections: 190,
    instructingAgent: 190,
    formalProofPreparation: 140,
    formalProofHearingPerHalfHour: 67,
    settlementConferencePreparation: 210,
    settlementConferenceHearingPerHalfHour: 67,
    memorandumOfConsent: 310,
    report: 190,
    additionalFactorsPreHearingMatters: 190,
    defendedHearingPreparation: 0,
    defendedHearingPerHalfHour: 67,
    directionsConferencePreparation: 140,
    directionsConferenceHearingPerHalfHour: 67,
    preHearingConferencePreparation: 140,
    preHearingConferenceHearingPerHalfHour: 67,
  },
  disbursements: {
    travelTimeHourlyRate: 63,
  },
  totalRules: {
    totalApplication: "Sum of Form32B fixed-fee rows that are triggered by the lawyer prompt.",
    totalDisbursementsExcludingMileage:
      "Sum of non-mileage disbursements, including travel time, parking, and office disbursements where placeholders exist.",
  },
} as const;

export const form32BSettingsStorageKey = "newgenautomation.form32b.management.settings";

export type Form32BRuleSettings = {
  wordingByRuleId: Record<string, string>;
  statusByRuleId: Record<string, Form33AManagementRule["status"]>;
  fixNotesByRuleId: Record<string, string>;
};

export type Form32BManagementRule = Form33AManagementRule;

export const form32BManagementRules: Form32BManagementRule[] = [
  {
    id: "pre-hearing-matters",
    section: "Pre-hearing matters",
    keyword: "pre hearing matters, pre-hearing matters",
    formRow: "Pre-Hearing Matters",
    placeholders: ["PHM"],
    quantityRule: "Single fixed amount; same value is used in both cells on the row.",
    feeRule: `$${form32BFeeRules.fixedFees.preHearingMatters} fixed fee.`,
    totalBucket: "Applicant fixed fees",
    gstTreatment: "GST applies through the total GST calculation.",
    standardWording:
      "Received defended Application - All correspondence and phone calls with client, court and counsel with respect to these proceedings. Advise client and instruct Counsel as to the Direction of the proceedings. Inform the Court of Direction required to advance the proceedings.",
    status: "Active",
    inactiveReason: "No blocker for the placeholder and price. Needs real prompt testing.",
    howToFix: "Run a pre-hearing matters prompt and confirm only PHM is filled.",
  },
  {
    id: "complying-judges-directions",
    section: "Pre-hearing matters",
    keyword: "complying with judges directions, judge directions",
    formRow: "Complying with Judge's directions",
    placeholders: ["CJD_QTY", "CJD_UNIT", "CJD_TOTAL"],
    quantityRule: "Single fixed amount. Quantity is 1 when triggered.",
    feeRule: `$${form32BFeeRules.fixedFees.complyingJudgesDirections} fixed fee.`,
    totalBucket: "Applicant fixed fees",
    gstTreatment: "GST applies through the total GST calculation.",
    standardWording:
      "Complying with Judges directions - the Court directed that parties file further evidence via an affidavit. This has now been completed.",
    status: "Active",
    inactiveReason: "No blocker for current placeholders.",
    howToFix: "Run a complying with Judge's directions prompt and confirm CJD row fills.",
  },
  {
    id: "instructing-agent",
    section: "Pre-hearing matters",
    keyword: "agent appears, instructing agent, agent appearance",
    formRow: "Instructing agent",
    placeholders: ["IA_QTY", "IA_TOTAL"],
    quantityRule: "Single fixed amount. The template has no IA_UNIT placeholder.",
    feeRule: `$${form32BFeeRules.fixedFees.instructingAgent} fixed fee.`,
    totalBucket: "Applicant fixed fees",
    gstTreatment: "GST applies through the total GST calculation.",
    standardWording:
      "Enclosed Notice of Fixture, Agents Report and invoice. Directions made as per Agent's Report. Briefing Agent - preparing written brief for Counsel. Attendance at Directions Conference on [billing date] from [attendance time].",
    status: "Partial",
    inactiveReason: "The flow chart references IA_UNIT, but the template only has IA_QTY and IA_TOTAL.",
    howToFix: "Either add {{IA_UNIT}} to the template or accept quantity and total only.",
  },
  {
    id: "formal-proof",
    section: "Formal proof",
    keyword: "formal proof, formal proof hearing",
    formRow: "Formal proof hearing(s) - Preparation; Formal proof hearing(s) - Hearing time",
    placeholders: ["FPH_P_QTY", "FPH_P_UNIT", "FPH_P_TOTAL", "FPH_H_QTY", "FPH_H_UNIT", "FPH_H_TOTAL"],
    quantityRule: "Preparation is 1. Hearing time is rounded up in 30 minute units.",
    feeRule: `$${form32BFeeRules.fixedFees.formalProofPreparation} preparation + $${form32BFeeRules.fixedFees.formalProofHearingPerHalfHour} per half hour hearing time.`,
    totalBucket: "Applicant fixed fees",
    gstTreatment: "GST applies through the total GST calculation.",
    standardWording:
      "Preparing for Formal Proof, taking client's instructions, advising of procedural steps, advising of what will take place at the Formal Proof hearing. All correspondence and calls with Counsel and parties. Enclosed Notice of Fixture. Directions made. Attendance at Formal Proof on [billing date] from [attendance time].",
    status: "Partial",
    inactiveReason: "The template has malformed FPH placeholders using {[...}}. The app handles them, but the template should be corrected later.",
    howToFix: "Replace malformed FPH placeholders with normal {{FPH_*}} placeholders in Word.",
  },
  {
    id: "settlement-conference",
    section: "Conferences",
    keyword: "settlement conference, sc, round table meeting",
    formRow: "Settlement Conference(s) - Preparation; Settlement Conference(s) - Hearing time",
    placeholders: ["SC_P_QTY", "SC_P_UNIT", "SC_P_TOTAL", "SC_H_QTY", "SC_H_UNIT", "SC_H_TOTAL"],
    quantityRule: "Preparation is 1. Hearing time is rounded up in 30 minute units.",
    feeRule: `$${form32BFeeRules.fixedFees.settlementConferencePreparation} preparation + $${form32BFeeRules.fixedFees.settlementConferenceHearingPerHalfHour} per half hour hearing time.`,
    totalBucket: "Applicant fixed fees",
    gstTreatment: "GST applies through the total GST calculation.",
    standardWording:
      "Prep settlement conference - review affidavit evidence, advise client of format and rules of engagement for meeting, seek client's instructions and advise client of strategy for the Settlement Conference. Attendance at Settlement Conference on [billing date] from [attendance time].",
    status: "Active",
    inactiveReason: "No blocker for current placeholders. Round table meeting uses the same row.",
    howToFix: "Test settlement conference and round table prompts to confirm wording preference.",
  },
  {
    id: "memorandum-of-consent",
    section: "Consent",
    keyword: "MOC, memorandum of consent, consent memorandum",
    formRow: "Memorandum of Consent",
    placeholders: ["MOC_QTY", "MOC_UNIT", "MOC_TOTAL"],
    quantityRule: "Single fixed amount.",
    feeRule: `$${form32BFeeRules.fixedFees.memorandumOfConsent} fixed fee.`,
    totalBucket: "Applicant fixed fees",
    gstTreatment: "GST applies through the total GST calculation.",
    standardWording: "The parties and Counsel have negotiated a consent memorandum to advance proceedings.",
    status: "Active",
    inactiveReason: "No blocker for current placeholders.",
    howToFix: "Run a memorandum of consent prompt and confirm only MOC row fills.",
  },
  {
    id: "report",
    section: "Reports",
    keyword: "s 132 report, s 133 report, LFC report, lawyer for child report",
    formRow: "Report",
    placeholders: ["SR_QTY", "SR_UNIT", "SR_TOTAL"],
    quantityRule: "Single fixed amount.",
    feeRule: `$${form32BFeeRules.fixedFees.report} fixed fee.`,
    totalBucket: "Applicant fixed fees",
    gstTreatment: "GST applies through the total GST calculation.",
    standardWording:
      "Receipt of report. Perusing report. Considering recommendations. Advising client of impact of report on proceedings.",
    status: "Active",
    inactiveReason: "No blocker for current placeholders. Wording may need separate variants for s132, s133 and LFC.",
    howToFix: "Test one example for s132, s133, and LFC report, then split wording if needed.",
  },
  {
    id: "additional-factors",
    section: "Additional factors",
    keyword: "additional factors",
    formRow: "Additional factors",
    placeholders: ["AF_PHM"],
    quantityRule: "Single fixed amount.",
    feeRule: `$${form32BFeeRules.fixedFees.additionalFactorsPreHearingMatters} fixed fee.`,
    totalBucket: "Applicant fixed fees",
    gstTreatment: "GST applies through the total GST calculation.",
    standardWording:
      "The Respondent is self represented and this makes negotiations very challenging and is causing delays in advancing proceedings.",
    status: "Active",
    inactiveReason: "No blocker for current placeholder. Lawyer should review wording before filing.",
    howToFix: "Use the management page wording box to refine this wording.",
  },
  {
    id: "defended-hearing",
    section: "Defended hearing",
    keyword: "short cause fixture, defended hearing",
    formRow: "Defended hearing - Preparation; Defended hearing - Hearing time",
    placeholders: ["DF_P_QTY", "DF_P_UNIT", "DF_P_TOTAL", "DF_H_QTY", "DF_H_UNIT", "DF_H_TOTAL"],
    quantityRule: "Preparation is 1. Hearing time is rounded up in 30 minute units.",
    feeRule: `$${form32BFeeRules.fixedFees.defendedHearingPerHalfHour} per half hour hearing time.`,
    totalBucket: "Applicant fixed fees",
    gstTreatment: "GST applies through the total GST calculation.",
    standardWording:
      "Defended Hearing - review file, prepare for defended hearing, cross examination, briefing witnesses, preparing submissions. Reporting to client. We attended at the Fixture on [billing date] from [attendance time].",
    status: "Active",
    inactiveReason: "No blocker for current placeholders.",
    howToFix: "Test defended hearing examples and confirm only the $67 per half hour hearing-time amount is claimed.",
  },
  {
    id: "directions-conference",
    section: "Conferences",
    keyword: "directions conference, direction conference, dc",
    formRow: "Directions Conference(s) - Preparation; Directions Conference(s) - Hearing time",
    placeholders: ["DC_P_QTY", "DC_P_UNIT", "DC_P_TOTAL", "DC_H_QTY", "DC_H_UNIT", "DC_H_TOTAL"],
    quantityRule: "Preparation is 1. Hearing time is rounded up in 30 minute units.",
    feeRule: `$${form32BFeeRules.fixedFees.directionsConferencePreparation} preparation + $${form32BFeeRules.fixedFees.directionsConferenceHearingPerHalfHour} per half hour hearing time.`,
    totalBucket: "Applicant fixed fees",
    gstTreatment: "GST applies through the total GST calculation.",
    standardWording:
      "Preparing for Directions Conference, taking client's instructions, advising of procedural steps, advising of what will take place at the Conference. All correspondence and calls with Counsel and parties. Enclosed Notice of Fixture. Directions granted to advance the proceedings. Attendance at Directions Conference on [billing date] from [attendance time].",
    status: "Active",
    inactiveReason: "No blocker for current placeholders.",
    howToFix: "Test a directions conference prompt and confirm DC row fills.",
  },
  {
    id: "pre-hearing-conference",
    section: "Conferences",
    keyword: "pre hearing conference, pre-hearing conference",
    formRow: "Pre-Hearing Conference - Preparation; Pre-Hearing Conference - Hearing time",
    placeholders: ["PHC_P_QTY", "PHC_P_UNIT", "PHC_P_TOTAL", "PHC_H_QTY", "PHC_H_UNIT", "PHC_H_TOTAL"],
    quantityRule: "Preparation is 1. Hearing time is rounded up in 30 minute units.",
    feeRule: `$${form32BFeeRules.fixedFees.preHearingConferencePreparation} preparation + $${form32BFeeRules.fixedFees.preHearingConferenceHearingPerHalfHour} per half hour hearing time.`,
    totalBucket: "Applicant fixed fees",
    gstTreatment: "GST applies through the total GST calculation.",
    standardWording:
      "All correspondence and phone calls with client, court and counsel with respect to these proceedings. Advise client and instruct Counsel as to the Direction of the proceedings. Inform the Court of Direction required to advance the proceedings.",
    status: "Active",
    inactiveReason: "No blocker for current placeholders.",
    howToFix: "Test a pre-hearing conference prompt and confirm PHC row fills.",
  },
];
