export type TemplateFieldCategory =
  | "Matter"
  | "Applicant"
  | "Respondent"
  | "Children"
  | "Relationship"
  | "Affidavit"
  | "Family violence"
  | "Legal aid"
  | "Workflow";

export type TemplateFieldDefinition = {
  key: string;
  label: string;
  category: TemplateFieldCategory;
  description: string;
  example: string;
  source: "intake" | "derived" | "workflow" | "drafting";
  format?: string;
};

export type LegacyTemplateAlias = {
  alias: string;
  canonical: string;
  reason: string;
};

export const templateFieldDefinitions: TemplateFieldDefinition[] = [
  {
    key: "matter_id",
    label: "Matter ID",
    category: "Matter",
    description: "Internal NewGen matter identifier.",
    example: "matter-178893",
    source: "derived",
  },
  {
    key: "fam_number",
    label: "FAM number",
    category: "Matter",
    description: "Family Court file number.",
    example: "FAM-2026-000001",
    source: "intake",
  },
  {
    key: "court_location",
    label: "Court location",
    category: "Matter",
    description: "English court location used in headings and filing text.",
    example: "NORTH SHORE",
    source: "derived",
    format: "Uppercase",
  },
  {
    key: "court_location_maori",
    label: "Court location Maori",
    category: "Matter",
    description: "Maori court heading for the selected court.",
    example: "TE KOTI-A-WHANAU KI OKAHUKURA",
    source: "derived",
    format: "Uppercase",
  },
  {
    key: "date_today",
    label: "Short date",
    category: "Matter",
    description: "Short date for signature/date fields.",
    example: "09/09/2026",
    source: "derived",
  },
  {
    key: "date_today_long",
    label: "Long date",
    category: "Matter",
    description: "Long date for letters and ordinary dated text.",
    example: "9 September 2026",
    source: "derived",
  },
  {
    key: "month_day",
    label: "Ordinal day",
    category: "Matter",
    description: "Ordinal day for court signing lines.",
    example: "9th",
    source: "derived",
  },
  {
    key: "month",
    label: "Month",
    category: "Matter",
    description: "Current month for court signing lines.",
    example: "September",
    source: "derived",
  },
  {
    key: "year",
    label: "Year",
    category: "Matter",
    description: "Current year for court signing lines.",
    example: "2026",
    source: "derived",
  },
  {
    key: "applicant_name",
    label: "Applicant name",
    category: "Applicant",
    description: "Applicant full name as used in court documents.",
    example: "STACEY LUPTON",
    source: "derived",
    format: "Uppercase",
  },
  {
    key: "applicant_first_name",
    label: "Applicant first name",
    category: "Applicant",
    description: "First word of the applicant name.",
    example: "STACEY",
    source: "derived",
    format: "Uppercase",
  },
  {
    key: "applicant_last_name",
    label: "Applicant last name",
    category: "Applicant",
    description: "Last word of the applicant name.",
    example: "Lupton",
    source: "derived",
  },
  {
    key: "applicant_last_name_upper",
    label: "Applicant last name uppercase",
    category: "Applicant",
    description: "Applicant surname for file references and captions.",
    example: "LUPTON",
    source: "derived",
    format: "Uppercase",
  },
  {
    key: "applicant_home_address",
    label: "Applicant home address",
    category: "Applicant",
    description: "Applicant residential address.",
    example: "1 Example Road, Auckland",
    source: "intake",
  },
  {
    key: "applicant_phone",
    label: "Applicant phone",
    category: "Applicant",
    description: "Applicant contact phone.",
    example: "021 000 0000",
    source: "intake",
  },
  {
    key: "applicant_phone_number",
    label: "Applicant phone number",
    category: "Applicant",
    description: "Alias used where templates say phone number.",
    example: "021 000 0000",
    source: "intake",
  },
  {
    key: "applicant_email",
    label: "Applicant email",
    category: "Applicant",
    description: "Applicant email address.",
    example: "stacey@example.com",
    source: "intake",
  },
  {
    key: "applicant_dob",
    label: "Applicant date of birth",
    category: "Applicant",
    description: "Applicant date of birth.",
    example: "01/01/1990",
    source: "intake",
  },
  {
    key: "applicant_age",
    label: "Applicant age",
    category: "Applicant",
    description: "Applicant age derived from date of birth.",
    example: "36",
    source: "derived",
  },
  {
    key: "applicant_occupation",
    label: "Applicant occupation",
    category: "Applicant",
    description: "Applicant occupation or benefit status.",
    example: "Beneficiary",
    source: "intake",
  },
  {
    key: "respondent_name",
    label: "Respondent name",
    category: "Respondent",
    description: "Respondent full name as used in court documents.",
    example: "ANTHONY CRAVEN",
    source: "derived",
    format: "Uppercase",
  },
  {
    key: "respondent_first_name",
    label: "Respondent first name",
    category: "Respondent",
    description: "First word of the respondent name.",
    example: "ANTHONY",
    source: "derived",
    format: "Uppercase",
  },
  {
    key: "respondent_last_name",
    label: "Respondent last name",
    category: "Respondent",
    description: "Last word of the respondent name.",
    example: "Craven",
    source: "derived",
  },
  {
    key: "respondent_last_name_upper",
    label: "Respondent last name uppercase",
    category: "Respondent",
    description: "Respondent surname for file references and captions.",
    example: "CRAVEN",
    source: "derived",
    format: "Uppercase",
  },
  {
    key: "respondent_home_address",
    label: "Respondent home address",
    category: "Respondent",
    description: "Respondent residential address.",
    example: "2 Example Street, Auckland",
    source: "intake",
  },
  {
    key: "respondent_phone",
    label: "Respondent phone",
    category: "Respondent",
    description: "Respondent contact phone.",
    example: "022 000 0000",
    source: "intake",
  },
  {
    key: "respondent_email",
    label: "Respondent email",
    category: "Respondent",
    description: "Respondent email address.",
    example: "respondent@example.com",
    source: "intake",
  },
  {
    key: "respondent_dob",
    label: "Respondent date of birth",
    category: "Respondent",
    description: "Respondent date of birth.",
    example: "02/02/1988",
    source: "intake",
  },
  {
    key: "respondent_age",
    label: "Respondent age",
    category: "Respondent",
    description: "Respondent age derived from date of birth.",
    example: "38",
    source: "derived",
  },
  {
    key: "respondent_occupation",
    label: "Respondent occupation",
    category: "Respondent",
    description: "Respondent occupation or benefit status.",
    example: "Unemployed",
    source: "intake",
  },
  {
    key: "respondent_work_address",
    label: "Respondent work address",
    category: "Respondent",
    description: "Respondent workplace address.",
    example: "3 Work Road, Auckland",
    source: "intake",
  },
  {
    key: "respondent_relationship_to_applicant",
    label: "Respondent relationship to applicant",
    category: "Respondent",
    description: "Relationship between respondent and applicant.",
    example: "former partner",
    source: "intake",
  },
  {
    key: "respondent_relationship_to_children",
    label: "Respondent relationship to children",
    category: "Respondent",
    description: "Joined child relationship values for parenting documents.",
    example: "father",
    source: "derived",
  },
  {
    key: "relationship_start_date",
    label: "Relationship start date",
    category: "Relationship",
    description: "Approximate start date of the relationship.",
    example: "1 March 2020",
    source: "intake",
  },
  {
    key: "relationship_end_date",
    label: "Relationship end date",
    category: "Relationship",
    description: "Relationship separation date.",
    example: "1 August 2026",
    source: "intake",
  },
  {
    key: "marriage_date",
    label: "Marriage date",
    category: "Relationship",
    description: "Marriage or civil union date.",
    example: "1 March 2020",
    source: "intake",
  },
  {
    key: "marriage_place",
    label: "Marriage place",
    category: "Relationship",
    description: "Marriage or civil union place.",
    example: "Auckland",
    source: "intake",
  },
  {
    key: "child_1_name",
    label: "Child 1 name",
    category: "Children",
    description: "First child's full name.",
    example: "CHILD ONE",
    source: "intake",
    format: "Uppercase",
  },
  {
    key: "child_1_firstname",
    label: "Child 1 first name",
    category: "Children",
    description: "First child's first name.",
    example: "CHILD",
    source: "derived",
  },
  {
    key: "child_1_dob",
    label: "Child 1 DOB",
    category: "Children",
    description: "First child's date of birth.",
    example: "01/01/2018",
    source: "intake",
  },
  {
    key: "child_1_age",
    label: "Child 1 age",
    category: "Children",
    description: "First child's age.",
    example: "8",
    source: "intake",
  },
  {
    key: "child_1_gender",
    label: "Child 1 gender",
    category: "Children",
    description: "First child's gender.",
    example: "F",
    source: "intake",
  },
  {
    key: "child_1_living_with",
    label: "Child 1 living with",
    category: "Children",
    description: "Person the first child lives with.",
    example: "Applicant",
    source: "intake",
  },
  {
    key: "child_1_relationship_to_applicant",
    label: "Child 1 relationship to applicant",
    category: "Children",
    description: "First child's relationship to the applicant.",
    example: "daughter",
    source: "intake",
  },
  {
    key: "child_1_relationship_to_respondent",
    label: "Child 1 relationship to respondent",
    category: "Children",
    description: "First child's relationship to the respondent.",
    example: "daughter",
    source: "intake",
  },
  {
    key: "child_1_ethnicity",
    label: "Child 1 ethnicity",
    category: "Children",
    description: "First child's ethnicity.",
    example: "New Zealand European",
    source: "intake",
  },
  {
    key: "previous_applications",
    label: "Previous applications",
    category: "Relationship",
    description: "Previous applications between the parties.",
    example: "None known",
    source: "intake",
  },
  {
    key: "existing_child_orders",
    label: "Existing child orders",
    category: "Relationship",
    description: "Existing orders relating to children.",
    example: "None",
    source: "intake",
  },
  {
    key: "existing_orders_between_parties",
    label: "Existing party orders",
    category: "Relationship",
    description: "Existing orders between applicant and respondent.",
    example: "None",
    source: "intake",
  },
  {
    key: "affidavit_application_title",
    label: "Affidavit application title",
    category: "Affidavit",
    description: "Generated title of the application supported by the affidavit.",
    example: "WITHOUT NOTICE APPLICATION FOR PROTECTION ORDER",
    source: "workflow",
  },
  {
    key: "application_intro",
    label: "Application intro",
    category: "Affidavit",
    description: "Generated opening affidavit application paragraph.",
    example: "I am applying without notice...",
    source: "workflow",
  },
  {
    key: "relationship_start_blurb",
    label: "Relationship start blurb",
    category: "Affidavit",
    description: "Generated prose describing relationship start.",
    example: "The Respondent and I were in a de facto relationship.",
    source: "workflow",
  },
  {
    key: "relationship_end_blurb",
    label: "Relationship end blurb",
    category: "Affidavit",
    description: "Generated prose describing separation.",
    example: "The Respondent and I split up on 1 August 2026.",
    source: "workflow",
  },
  {
    key: "children_blurb",
    label: "Children blurb",
    category: "Affidavit",
    description: "Generated children paragraph for affidavits.",
    example: "There is one child of the relationship.",
    source: "workflow",
  },
  {
    key: "violence_categories",
    label: "Violence categories",
    category: "Family violence",
    description: "Generated family violence category list.",
    example: "(a) Physical abuse.",
    source: "workflow",
  },
  {
    key: "family_violence_categories",
    label: "Family violence categories",
    category: "Family violence",
    description: "Selected category list for Plumsail-style templates.",
    example: "Physical abuse; Psychological abuse",
    source: "intake",
  },
  {
    key: "physical_abuse_selected",
    label: "Physical abuse selected",
    category: "Family violence",
    description: "Boolean flag for conditional template sections.",
    example: "true",
    source: "intake",
  },
  {
    key: "psychological_abuse_selected",
    label: "Psychological abuse selected",
    category: "Family violence",
    description: "Boolean flag for conditional template sections.",
    example: "true",
    source: "intake",
  },
  {
    key: "damage_to_property_selected",
    label: "Damage to property selected",
    category: "Family violence",
    description: "Boolean flag for conditional template sections.",
    example: "false",
    source: "intake",
  },
  {
    key: "sexual_abuse_selected",
    label: "Sexual abuse selected",
    category: "Family violence",
    description: "Boolean flag for conditional template sections.",
    example: "false",
    source: "intake",
  },
  {
    key: "legal_aid_number",
    label: "Legal aid number",
    category: "Legal aid",
    description: "Legal aid file number.",
    example: "LA-123456",
    source: "intake",
  },
  {
    key: "client_msd_number",
    label: "Client MSD number",
    category: "Legal aid",
    description: "Client number used for MSD requests.",
    example: "123456789",
    source: "intake",
  },
  {
    key: "msd_client_number",
    label: "MSD client number",
    category: "Legal aid",
    description: "Alias for client MSD number used by older templates.",
    example: "123456789",
    source: "intake",
  },
];

export const legacyTemplateAliases: LegacyTemplateAlias[] = [
  { alias: "APPLICANT_NAME", canonical: "applicant_name", reason: "Use lowercase snake_case in templates." },
  { alias: "Applicant_Name", canonical: "applicant_name", reason: "Use lowercase snake_case in templates." },
  { alias: "applicant_fullname", canonical: "applicant_name", reason: "Use one full-name field." },
  { alias: "APPLICANT_FIRST_NAME", canonical: "applicant_first_name", reason: "Use lowercase snake_case in templates." },
  { alias: "RESPONDENT_NAME", canonical: "respondent_name", reason: "Use lowercase snake_case in templates." },
  { alias: "Respondents_name", canonical: "respondent_name", reason: "Avoid plural/possessive role names." },
  { alias: "APPLICANT_SURNAME", canonical: "applicant_last_name_upper", reason: "Use explicit surname casing field." },
  { alias: "APPLCIANT_LAST_NAME", canonical: "applicant_last_name_upper", reason: "Fix spelling and casing." },
  { alias: "RESPONDENT_LAST_NAME", canonical: "respondent_last_name_upper", reason: "Use explicit surname casing field." },
  { alias: "COURT_NAME", canonical: "court_location", reason: "Use one court location field." },
  { alias: "MAORI_COURT_NAME", canonical: "court_location_maori", reason: "Use one Maori court location field." },
  { alias: "English_court_name", canonical: "court_location", reason: "Use lowercase snake_case in templates." },
  { alias: "Maori_court_name", canonical: "court_location_maori", reason: "Use lowercase snake_case in templates." },
  { alias: "Date_today", canonical: "date_today", reason: "Use lowercase snake_case in templates." },
  { alias: "todays_date", canonical: "date_today", reason: "Use one short date field." },
  { alias: "dd day of month year", canonical: "month_day day of month year", reason: "Use court signing date fields." },
  { alias: "Client_MSD_Number", canonical: "client_msd_number", reason: "Use lowercase snake_case in templates." },
  { alias: "Appliant_name_bold_capitals ", canonical: "applicant_name", reason: "Fix spelling; formatting belongs in Word." },
  { alias: "Applicant_name_bold_captals", canonical: "applicant_name", reason: "Fix spelling; formatting belongs in Word." },
  { alias: "Respondnet_name_bold_capital", canonical: "respondent_name", reason: "Fix spelling; formatting belongs in Word." },
  { alias: "applicants_address", canonical: "applicant_home_address", reason: "Use canonical applicant address." },
  { alias: "dd/month/yyyy", canonical: "applicant_dob", reason: "Use applicant DOB field." },
  { alias: "occupation", canonical: "applicant_occupation or respondent_occupation", reason: "Occupation must be role-specific." },
];

export const supplementalCanonicalTemplateFieldKeys = [
  "application_type_1",
  "application_type_2",
  "application_type_3",
  "applicant_ethnicity",
  "respondent_ethnicity",
  "child_2_name",
  "child_2_firstname",
  "child_2_dob",
  "child_2_age",
  "child_2_gender",
  "child_2_living_with",
  "child_2_relationship_to_applicant",
  "child_2_relationship_to_respondent",
  "child_2_ethnicity",
  "child_3_name",
  "child_3_firstname",
  "child_3_dob",
  "child_3_age",
  "child_3_gender",
  "child_3_living_with",
  "child_3_relationship_to_applicant",
  "child_3_relationship_to_respondent",
  "child_3_ethnicity",
  "child_4_name",
  "child_4_firstname",
  "child_4_dob",
  "child_4_age",
  "child_4_gender",
  "child_4_living_with",
  "child_4_relationship_to_applicant",
  "child_4_relationship_to_respondent",
  "child_4_ethnicity",
  "insert_history_blurb",
  "insert_recent_events_blurb",
  "protection_facts_heading",
  "without_notice_heading",
  "without_notice_intro",
  "without_notice_safety",
  "parenting_heading",
  "parenting_blurb",
  "orders_sought_blurb",
] as const;

export const canonicalTemplateFieldKeys = [
  ...templateFieldDefinitions.map((field) => field.key),
  ...supplementalCanonicalTemplateFieldKeys,
];

export const canonicalTemplateFieldSet = new Set(canonicalTemplateFieldKeys);

export const legacyTemplateAliasMap = new Map(legacyTemplateAliases.map((alias) => [alias.alias, alias]));

export function getFieldDefinition(key: string): TemplateFieldDefinition | undefined {
  return templateFieldDefinitions.find((field) => field.key === key);
}

export function getFieldsByCategory(): Array<[TemplateFieldCategory, TemplateFieldDefinition[]]> {
  const categories: TemplateFieldCategory[] = [
    "Matter",
    "Applicant",
    "Respondent",
    "Children",
    "Relationship",
    "Affidavit",
    "Family violence",
    "Legal aid",
    "Workflow",
  ];

  return categories.map((category) => [
    category,
    templateFieldDefinitions.filter((field) => field.category === category),
  ]);
}
